
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111

  flyway:
    locations: classpath:db/migration
    enabled: true